# Generated by Django 5.2.5 on 2025-08-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_is_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_author",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_author",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user can create and edit blog posts.",
            ),
        ),
    ]
